services:
  - type: web
    name: barbershop-mi-1
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: APP_NAME
        value: Barbershop
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false   # Lo defines manualmente en el dashboard
      - key: APP_URL
        value: https://barbershop-mi-1.onrender.com
      - key: DB_CONNECTION
        value: mongodb
      - key: MONGODB_URI
        sync: false   # Pega tu URI de MongoDB Atlas
      - key: MONGODB_DATABASE
        value: barbershop1
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: MERCADOPAGO_CURRENCY
        value: COP
      - key: MERCADOPAGO_BACK_URL_BASE
        sync: false   # Tu URL de Render: https://barbershop-mi-1.onrender.com
